### ISSUE TITLE
메서드 추가 구현 및 에러 고치기 및 통합테스트 진행

### ISSUE THREAD

**Issue by spew11** [izone00/webserv#67]
진행할 사항은 아래와 같습니다. 혹시 빠졌거나 더 필요하다싶은게 있다면 알려주세요 ^.^

- [x] methodExecutor::putMethod() 구현하기
- [x] HttpResponseBuilder 생성자에서 변수들 추가 초기화하기
- [x] url이 디렉토리일시에 index 이름 붙이기 전에 url뒤에 '/'없으면 '/'붙여주기
- [x] 오토인덱스 구현하기
- [x] cgi 생성물 파싱할 때 헤더가 여러개일 수 있음을 고려하기
- [x] ServerError 클래스 및 메소드들 이름 더 적합하게 바꾸기
- [x] response body가 없을 때 메서드를 체크하여 필요할 때 만 응답페이지 생성하기
- [x] body_max_size 지시어 고려하여 메서드 작성하기
- [ ] 요청 메시지가 짤려서 여러번 나눠오는 것을 고려한 관련 메서드 만들기
- [x] http요청의 connetion 헤더 확인하고 값이 close일시 사용자(소영이)에게 알리기
- [ ] error_page 지시어 고려하기(리다이렉트)

**Comment by izone00** [comment]
서브젝트를 보니깐  error_page라는 지시어를 다시 추가 해야 될것 같아요!

예)
error_page 500 501 502 /50x.html
